In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow' from '/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py'>


In [2]:
# tensors
string = tf.Variable("this is a vector",tf.string)
number = tf.Variable(10,tf.int16)
floating = tf.Variable(10.48,tf.float64)
print(string,number,floating,sep="\n")

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a vector'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.48>


In [3]:
# rank and shape
rank0_tensor = tf.Variable(1,tf.int8)
rank1_tensor = tf.Variable([1,2,3,4],tf.int32)
rank2_tensor = tf.Variable([[1,2],[3,4]],tf.int32)
print(rank0_tensor,rank1_tensor,rank2_tensor,sep="\n")
print("-"*50)
print(rank2_tensor.shape,rank1_tensor.shape,rank0_tensor.shape)                    # shape will tell the dimensions
print("-"*50)
print(tf.rank(rank2_tensor),tf.rank(rank1_tensor),tf.rank(rank0_tensor),sep="\n")  # rank will tell the highest branching

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
--------------------------------------------------
(2, 2) (4,) ()
--------------------------------------------------
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [4]:
# ones,zeros and reshape
tensor1 = tf.ones([3,3,1])
tensor2 = tf.reshape(tensor1,[3,1,3])
tensor3 = tf.reshape(tensor2,[3,-1])
tensor0 = tf.zeros([3,3,3])
print(tensor1)
print(tensor2)
print(tensor3)
print(tensor0)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(3, 3, 1), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(3, 1, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


In [5]:
print(tensor0)
print(tf.reshape(tensor0,[9,-1]))
print(tf.reshape(tensor0,[3,-1]))

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(9, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(3, 9), dtype=float32)


In [6]:
# types of tensors
# Variable,Constant,Placeholder,SparseTensor
# are immutable