In [6]:
ltx_rate = 0.05
rfd_rate = 0.43
income = 250000
income_aftertax = income - (income * ltx_rate)
print(f"The income after the tax : {income_aftertax}")

The income after the tax : 237500.0


In [ ]:
print("Sudashan "*5)

Sudarshan Sudarshan Sudarshan Sudarshan Sudarshan 


In [7]:
income_rfld = income -  income * rfd_rate
print(f"the income after the rlfd is {income_rfld}")

the income after the rlfd is 142500.0


In [8]:
login = input("Enter the login : ")
language = input("Enter the language : ")
print(f"The login is {login} and the language is {language}")

Enter the login : Sudarshan
Enter the language : English
The login is Sudarshan and the language is English


In [10]:
hours = float(input("How many hours did u work last month : "))
rate = float(input(" What is ur hourly rate: "))
print(f"last month, you earned {hours*rate} dollars")

How many hours did u work last month : 30
 What is ur hourly rate: 10.5
last month, you earned 315.0 dollars


In [ ]:
# refund policy
days = int(input("How many days before did u purchase it : "))
use = input("Item usage[Y/N] : ")
ownBroke = input("did it break on its own [Y/N] : ")

if days<=10 and use=='N' and ownBroke=="Y":
  print("Refund is possible")
else:
  print("refund not possible")

In [26]:
while 1:
  year = int(input("Enter the year : "))
  if year >1994:
    print("It was earlier..guess again")
  elif year<1994:
    print("It was later..guess again")
  else:
    print("Right guess")
    break

Enter the year : 1
It was later..guess again
Enter the year : 1994
Right guess


#numpy

In [61]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("1D array :",arr,"\n",type(arr))

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array :",arr1,"\n",type(arr1))

# rng = np.random.default_rng(12345)
rints = np.random.randint(low=0, high=10, size=4)
print(rints)


1D array : [1 2 3 4 5] 
 <class 'numpy.ndarray'>
2D array : [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 <class 'numpy.ndarray'>
[1 9 7 4]


In [ ]:
#arthematic operations

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])

print(arr1+arr2,"\n")
print(arr1*arr2,"\n")
print(arr1-arr2,"\n")
print(arr2-arr1,"\n")
print(arr1 @ arr2,"\n")
print(arr1 / arr2,"\n")
print(arr1 ** 3,"\n")

In [60]:
# zeros
zeros = np.zeros((3,3),dtype=np.int8)
print(zeros)
print(zeros.shape)
print(zeros.size)
print(zeros.dtype)
print(zeros.itemsize)
print(zeros.ndim)
print()
#ones
ones = np.ones((2,2))
print(ones)
print(ones.shape)
print(ones.size)
print(ones.dtype)
print(ones.itemsize)
print(ones.ndim)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
9
int8
1
2

[[1. 1.]
 [1. 1.]]
(2, 2)
4
float64
8
2
