<a href="https://colab.research.google.com/github/NagulapalliSudarshan/MachineLearning/blob/main/Learning/ML_lab_sem5/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# training and testing iris data

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris_data = load_iris()
print(iris_data,type(iris_data),sep="\n")


In [ ]:
print(iris_data.keys())
print(iris_data.target_names)
print(iris_data.feature_names)

In [ ]:
data_features = iris_data.data
data_target = iris_data.target
print(data_features)
print(data_target)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data_features,data_target,test_size=0.4,random_state = 1)
print(x_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y_train.shape)

# SimpleImputer

In [ ]:
# simpleImputer
# for handling null values in the dataset

import numpy as np
from sklearn.impute import SimpleImputer
imp_learner = SimpleImputer(missing_values = np.nan,strategy="mean")
print(imp_learner)

data = [[12,np.nan,34],[10,32,np.nan],[np.nan,11,20]]
print(data)

imp_learner = imp_learner.fit(data)
print(imp_learner)
data = imp_learner.transform(data)
print(data)

SimpleImputer()
[[12, nan, 34], [10, 32, nan], [nan, 11, 20]]
SimpleImputer()
[[12.  21.5 34. ]
 [10.  32.  27. ]
 [11.  11.  20. ]]


# LabelEncoder

In [ ]:
import pandas as pd

my_data = {
    "Gender" : ['F', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'M'],
    "Name" : ['Cindy', 'Carl', 'Johnny', 'Stacey', 'Andy', 'Sara', 'Victor', 'Martha', 'Mindy', 'Max']
        }
# print(my_data)

my_df = pd.DataFrame(my_data)
print(my_df)

count=0
for i in range(len(my_df['Gender'])):
  if my_df["Gender"][i]=="M":
    my_df["Gender"][i]=1
  else:
    my_df["Gender"][i]=0
# print(count)
print(my_df)

print(my_df['Gender'].unique())




  Gender    Name
0      F   Cindy
1      M    Carl
2      M  Johnny
3      F  Stacey
4      M    Andy
5      F    Sara
6      M  Victor
7      F  Martha
8      F   Mindy
9      M     Max
  Gender    Name
0      0   Cindy
1      1    Carl
2      1  Johnny
3      0  Stacey
4      1    Andy
5      0    Sara
6      1  Victor
7      0  Martha
8      0   Mindy
9      1     Max
[0 1]


#Binarizer


In [ ]:
import numpy as np
from sklearn.preprocessing import Binarizer
data = np.array([[3, -1.5, 2, -5.4], [0, 4, -0.3, 2.1], [1, 3.3,-1.9,-4.3]])
print("---Orginal data.............")
print(data)
data_binarized = Binarizer(threshold=1.4).transform(data)
print("...After Binarizer...... ")
print(data_binarized)

---Orginal data.............
[[ 3.  -1.5  2.  -5.4]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]
...After Binarizer...... 
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]
